# Generated by Django 5.0.7 on 2026-01-12 13:24

import django.db.models.deletion
import django.utils.timezone
import loyalty.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('pos_api_key', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('phone_verified', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('CASHIER', 'Cashier'), ('ADMIN', 'Admin')], default='CLIENT', max_length=16)),
                ('otp_code', models.CharField(blank=True, max_length=8)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='loyalty.tenant')),
            ],
            managers=[
                ('objects', loyalty.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=16)),
                ('current_points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='loyalty.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='loyalty.loyaltycard')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pos_api_key', models.CharField(blank=True, max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='loyalty.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earn_percent', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='loyalty.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='loyalty.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'location')},
            },
        ),
        migrations.CreateModel(
            name='LoyaltyOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EARN', 'Earn'), ('REDEEM', 'Redeem')], max_length=8)),
                ('source', models.CharField(choices=[('POS', 'POS'), ('CASHIER_APP', 'CashierApp')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('points', models.IntegerField(default=0)),
                ('receipt_id', models.CharField(blank=True, max_length=64, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=16)),
                ('fail_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='loyalty.loyaltycard')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyalty.location')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_operations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='loyalty.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'receipt_id'], name='loyalty_loy_tenant__121bf9_idx'), models.Index(fields=['tenant', 'idempotency_key'], name='loyalty_loy_tenant__0ed1be_idx'), models.Index(fields=['card', 'created_at'], name='loyalty_loy_card_id_9737c6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('tenant', 'email'), name='uniq_user_email_per_tenant'),
        ),
    ]
