# Generated by Django 5.0.7 on 2026-01-12 17:26

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_align_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverificationcode',
            new_name='loyalty_ema_user_id_82a3db_idx',
            old_name='loyalty_ema_user_id_0f9815_idx',
        ),
        migrations.AlterField(
            model_name='loyaltyoperation',
            name='source',
            field=models.CharField(choices=[('POS', 'POS'), ('CASHIER_APP', 'CashierApp'), ('ADMIN_PORTAL', 'AdminPortal')], max_length=16),
        ),
        migrations.AlterField(
            model_name='loyaltyoperation',
            name='type',
            field=models.CharField(choices=[('EARN', 'Earn'), ('REDEEM', 'Redeem'), ('REFUND', 'Refund')], max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
