# Generated by Codex on 2026-01-14
from django.db import migrations, models
import django.db.models.deletion


def backfill_tenant(apps, schema_editor):
    Tenant = apps.get_model("loyalty", "Tenant")
    StaffProfile = apps.get_model("loyalty", "StaffProfile")
    OneTimeQR = apps.get_model("loyalty", "OneTimeQR")
    CouponAssignment = apps.get_model("loyalty", "CouponAssignment")
    EmailVerificationCode = apps.get_model("loyalty", "EmailVerificationCode")

    default_tenant, _ = Tenant.objects.get_or_create(
        slug="default",
        defaults={
            "name": "Default Tenant",
            "pos_api_key": "",
        },
    )

    for profile in StaffProfile.objects.filter(tenant__isnull=True):
        tenant = getattr(profile.user, "tenant", None) or default_tenant
        profile.tenant_id = tenant.id
        profile.save(update_fields=["tenant"])

    for qr in OneTimeQR.objects.filter(tenant__isnull=True):
        tenant = getattr(qr.card, "tenant", None) or default_tenant
        qr.tenant_id = tenant.id
        qr.save(update_fields=["tenant"])

    for assignment in CouponAssignment.objects.filter(tenant__isnull=True):
        tenant = getattr(assignment.card, "tenant", None) or getattr(assignment.coupon, "tenant", None) or default_tenant
        assignment.tenant_id = tenant.id
        assignment.save(update_fields=["tenant"])

    for code in EmailVerificationCode.objects.filter(tenant__isnull=True):
        tenant = getattr(code.user, "tenant", None) or default_tenant
        code.tenant_id = tenant.id
        code.save(update_fields=["tenant"])


class Migration(migrations.Migration):

    dependencies = [
        ("loyalty", "0004_rename_loyalty_ema_user_id_0f9815_idx_loyalty_ema_user_id_82a3db_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="tenant",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="staff_profiles", to="loyalty.tenant"),
        ),
        migrations.AddField(
            model_name="onetimeqr",
            name="tenant",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="qr_tokens", to="loyalty.tenant"),
        ),
        migrations.AddField(
            model_name="couponassignment",
            name="tenant",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="coupon_assignments", to="loyalty.tenant"),
        ),
        migrations.AddField(
            model_name="emailverificationcode",
            name="tenant",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="email_codes", to="loyalty.tenant"),
        ),
        migrations.RunPython(backfill_tenant, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="staffprofile",
            name="tenant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="staff_profiles", to="loyalty.tenant"),
        ),
        migrations.AlterField(
            model_name="onetimeqr",
            name="tenant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="qr_tokens", to="loyalty.tenant"),
        ),
        migrations.AlterField(
            model_name="couponassignment",
            name="tenant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="coupon_assignments", to="loyalty.tenant"),
        ),
        migrations.AlterField(
            model_name="emailverificationcode",
            name="tenant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="email_codes", to="loyalty.tenant"),
        ),
        migrations.RemoveIndex(
            model_name="emailverificationcode",
            name="loyalty_ema_user_id_82a3db_idx",
        ),
        migrations.AddIndex(
            model_name="emailverificationcode",
            index=models.Index(fields=["tenant", "user", "is_used"], name="loyalty_ema_tenant_user_used_idx"),
        ),
        migrations.AddIndex(
            model_name="emailverificationcode",
            index=models.Index(fields=["tenant", "created_at"], name="loyalty_ema_tenant_created_idx"),
        ),
        migrations.AddIndex(
            model_name="onetimeqr",
            index=models.Index(fields=["tenant", "token"], name="loyalty_qr_tenant_token_idx"),
        ),
        migrations.AddIndex(
            model_name="onetimeqr",
            index=models.Index(fields=["tenant", "created_at"], name="loyalty_qr_tenant_created_idx"),
        ),
        migrations.AddIndex(
            model_name="couponassignment",
            index=models.Index(fields=["tenant", "created_at"], name="loyalty_coupon_tenant_created_idx"),
        ),
        migrations.AddIndex(
            model_name="couponassignment",
            index=models.Index(fields=["tenant", "status"], name="loyalty_coupon_tenant_status_idx"),
        ),
    ]
