# Generated by Django 5.0.7 on 2026-01-18 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0010_otp_codes_and_phone_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'Журнал аудита', 'verbose_name_plural': 'Журналы аудита'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Купон', 'verbose_name_plural': 'Купоны'},
        ),
        migrations.AlterModelOptions(
            name='couponassignment',
            options={'verbose_name': 'Выданный купон', 'verbose_name_plural': 'Выданные купоны'},
        ),
        migrations.AlterModelOptions(
            name='emailverificationcode',
            options={'verbose_name': 'Код подтверждения email', 'verbose_name_plural': 'Коды подтверждения email'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='loyaltycard',
            options={'verbose_name': 'Карта лояльности', 'verbose_name_plural': 'Карты лояльности'},
        ),
        migrations.AlterModelOptions(
            name='loyaltyoperation',
            options={'verbose_name': 'Операция лояльности', 'verbose_name_plural': 'Операции лояльности'},
        ),
        migrations.AlterModelOptions(
            name='loyaltyrule',
            options={'verbose_name': 'Правило лояльности', 'verbose_name_plural': 'Правила лояльности'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения'},
        ),
        migrations.AlterModelOptions(
            name='onetimeqr',
            options={'verbose_name': 'Одноразовый QR-код', 'verbose_name_plural': 'Одноразовые QR-коды'},
        ),
        migrations.AlterModelOptions(
            name='organizationsettings',
            options={'verbose_name': 'Настройки организации', 'verbose_name_plural': 'Настройки организации'},
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'verbose_name': 'Профиль сотрудника', 'verbose_name_plural': 'Профили сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'Арендатор', 'verbose_name_plural': 'Арендаторы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RenameIndex(
            model_name='couponassignment',
            new_name='loyalty_cou_tenant__928f87_idx',
            old_name='loyalty_coupon_tenant_created_idx',
        ),
        migrations.RenameIndex(
            model_name='couponassignment',
            new_name='loyalty_cou_tenant__8653a9_idx',
            old_name='loyalty_coupon_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverificationcode',
            new_name='loyalty_ema_tenant__96d6ed_idx',
            old_name='loyalty_ema_tenant_user_used_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverificationcode',
            new_name='loyalty_ema_tenant__ee322a_idx',
            old_name='loyalty_ema_tenant_created_idx',
        ),
        migrations.RenameIndex(
            model_name='offerredemption',
            new_name='loyalty_off_tenant__222da0_idx',
            old_name='loyalty_offe_tenant__f7dc32_idx',
        ),
        migrations.RenameIndex(
            model_name='offerredemption',
            new_name='loyalty_off_tenant__ae4374_idx',
            old_name='loyalty_offe_tenant__7bfc0c_idx',
        ),
        migrations.RenameIndex(
            model_name='offertarget',
            new_name='loyalty_off_tenant__38c2c5_idx',
            old_name='loyalty_offe_tenant__ae2c63_idx',
        ),
        migrations.RenameIndex(
            model_name='offertarget',
            new_name='loyalty_off_tenant__1a45f8_idx',
            old_name='loyalty_offe_tenant__b2d05f_idx',
        ),
        migrations.RenameIndex(
            model_name='onetimecode',
            new_name='loyalty_one_tenant__908a91_idx',
            old_name='loyalty_onet_tenant__1e5b6e_idx',
        ),
        migrations.RenameIndex(
            model_name='onetimecode',
            new_name='loyalty_one_tenant__c215fc_idx',
            old_name='loyalty_onet_tenant__0f12b4_idx',
        ),
        migrations.RenameIndex(
            model_name='onetimecode',
            new_name='loyalty_one_tenant__9a323b_idx',
            old_name='loyalty_onet_tenant__1b6b0b_idx',
        ),
        migrations.RenameIndex(
            model_name='onetimeqr',
            new_name='loyalty_one_tenant__58a45a_idx',
            old_name='loyalty_qr_tenant_token_idx',
        ),
        migrations.RenameIndex(
            model_name='onetimeqr',
            new_name='loyalty_one_tenant__f1571f_idx',
            old_name='loyalty_qr_tenant_created_idx',
        ),
        migrations.RenameIndex(
            model_name='ruletarget',
            new_name='loyalty_rul_tenant__93434f_idx',
            old_name='loyalty_rule_tenant__a870a1_idx',
        ),
        migrations.RenameIndex(
            model_name='ruletarget',
            new_name='loyalty_rul_tenant__4f9139_idx',
            old_name='loyalty_rule_tenant__f28a35_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=64, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='loyalty.tenant', verbose_name='Арендатор'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Активно с'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Активно по'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=32, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='loyalty.tenant', verbose_name='Арендатор'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='couponassignment',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_assignments', to='loyalty.loyaltycard', verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='couponassignment',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='loyalty.coupon', verbose_name='Купон'),
        ),
        migrations.AlterField(
            model_name='couponassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='couponassignment',
            name='status',
            field=models.CharField(choices=[('UNUSED', 'Не использован'), ('USED', 'Использован')], default='UNUSED', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='couponassignment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_assignments', to='loyalty.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='couponassignment',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Использован'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='attempts',
            field=models.IntegerField(default=0, verbose_name='Попытки'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(max_length=6, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Истекает'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Использован'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя отправка'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_codes', to='loyalty.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='location',
            name='pos_api_key',
            field=models.CharField(blank=True, max_length=64, verbose_name='POS API ключ'),
        ),
        migrations.AlterField(
            model_name='location',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='loyalty.tenant', verbose_name='Арендатор'),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='current_points',
            field=models.IntegerField(default=0, verbose_name='Текущие баллы'),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активна'), ('BLOCKED', 'Заблокирована')], default='ACTIVE', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='loyalty.tenant', verbose_name='Арендатор'),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='tier',
            field=models.CharField(default='Bronze', max_length=16, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='loyaltyoperation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='loyaltyoperation',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='loyalty.loyaltycard', verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='loyaltyoperation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='loyaltyoperation',
            name='fail_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина ошибки'),
        ),
        migrations.AlterField(
            model_name='loyaltyoperation',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Ключ идемпотентности'),
        ),
        migrations.AlterField(
            model_name='loyaltyoperation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyalty.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='loyaltyoperation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='loyaltyoperation',
            name='order_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='loyaltyoperation',
            name='original_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyalty.loyaltyoperation', verbose_name='Операция-источник'),
        ),
        migrations.AlterField(
            model_name='loyaltyoperation',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='loyaltyoperation',
            name='receipt_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Чек'),
        ),
        migrations.AlterField(
            model_name='loyaltyoperation',
            name='source',
            field=models.CharField(choices=[('POS', 'POS'), ('CASHIER_APP', 'Касса'), ('ADMIN_PORTAL', 'Админ-портал')], max_length=16, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='loyaltyoperation',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_operations', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='loyaltyoperation',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Успешно'), ('FAILED', 'Ошибка')], default='SUCCESS', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='loyaltyoperation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='loyalty.tenant', verbose_name='Арендатор'),
        ),
        migrations.AlterField(
            model_name='loyaltyoperation',
            name='type',
            field=models.CharField(choices=[('EARN', 'Начисление'), ('REDEEM', 'Списание'), ('REFUND', 'Возврат')], max_length=8, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='loyaltyrule',
            name='bronze_threshold',
            field=models.IntegerField(default=0, verbose_name='Порог Bronze'),
        ),
        migrations.AlterField(
            model_name='loyaltyrule',
            name='earn_percent',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='Процент начисления'),
        ),
        migrations.AlterField(
            model_name='loyaltyrule',
            name='gold_threshold',
            field=models.IntegerField(default=1500, verbose_name='Порог Gold'),
        ),
        migrations.AlterField(
            model_name='loyaltyrule',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='loyalty.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='loyaltyrule',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Минимальная сумма'),
        ),
        migrations.AlterField(
            model_name='loyaltyrule',
            name='rounding_mode',
            field=models.CharField(choices=[('FLOOR', 'Вниз'), ('ROUND', 'Округлить'), ('CEIL', 'Вверх')], default='FLOOR', max_length=8, verbose_name='Режим округления'),
        ),
        migrations.AlterField(
            model_name='loyaltyrule',
            name='silver_threshold',
            field=models.IntegerField(default=500, verbose_name='Порог Silver'),
        ),
        migrations.AlterField(
            model_name='loyaltyrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='loyalty.tenant', verbose_name='Арендатор'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='active_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Активно с'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='active_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Активно по'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='bonus_points',
            field=models.IntegerField(default=0, verbose_name='Бонусные баллы'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Множитель'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='loyalty.tenant', verbose_name='Арендатор'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(choices=[('MULTIPLIER', 'Множитель'), ('BONUS', 'Бонус'), ('COUPON', 'Купон')], default='BONUS', max_length=16, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='onetimeqr',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='loyalty.loyaltycard', verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='onetimeqr',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='onetimeqr',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Истекает'),
        ),
        migrations.AlterField(
            model_name='onetimeqr',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='loyalty.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='onetimeqr',
            name='token',
            field=models.CharField(max_length=64, unique=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='onetimeqr',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Использован'),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='brand_color',
            field=models.CharField(default='#2d6a4f', max_length=12, verbose_name='Цвет бренда'),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='email_from',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email отправителя'),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='logo_url',
            field=models.URLField(blank=True, verbose_name='URL логотипа'),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='loyalty.tenant', verbose_name='Арендатор'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyalty.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to='loyalty.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='pos_api_key',
            field=models.CharField(blank=True, max_length=64, verbose_name='POS API ключ'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email подтверждён'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_attempts',
            field=models.IntegerField(default=0, verbose_name='Попытки OTP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OTP истекает'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='OTP хеш'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OTP запрошен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='Телефон подтверждён'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Клиент'), ('CASHIER', 'Кассир'), ('ADMIN', 'Администратор')], default='CLIENT', max_length=16, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='loyalty.tenant', verbose_name='Арендатор'),
        ),
    ]
