from django.urls import path
from .views import (
    RegisterView,
    LoginView,
    ClientLoginView,
    CashierLoginView,
    AdminLoginView,
    EmailRequestCodeView,
    EmailConfirmView,
    PhoneRequestView,
    PhoneConfirmView,
    TelegramStartView,
    TelegramVerifyView,
    TelegramWebhookView,
    AuthMeView,
    ClientMeView,
    ClientOperationsView,
    ClientOffersView,
    ClientOfferUseView,
    ClientCouponsView,
    ClientQRIssueView,
    ClientPasswordChangeView,
    LoyaltyQRValidateView,
    LoyaltyEarnView,
    LoyaltyRedeemView,
    LoyaltyRefundView,
    POSLoyaltyEarnView,
    CashierOperationsView,
    AdminDashboardView,
    AdminCustomersView,
    AdminStaffView,
    AdminLocationsView,
    AdminRulesView,
    AdminOperationsView,
    AdminOffersView,
    AdminSettingsView,
)

urlpatterns = [
    path("t/<slug:tenant_slug>/auth/register", RegisterView.as_view()),
    path("t/<slug:tenant_slug>/auth/login", LoginView.as_view()),
    path("t/<slug:tenant_slug>/auth/client/login", ClientLoginView.as_view()),
    path("t/<slug:tenant_slug>/auth/cashier/login", CashierLoginView.as_view()),
    path("t/<slug:tenant_slug>/auth/admin/login", AdminLoginView.as_view()),
    path("t/<slug:tenant_slug>/auth/me", AuthMeView.as_view()),
    path("t/<slug:tenant_slug>/auth/verify-email", EmailConfirmView.as_view()),
    path("t/<slug:tenant_slug>/auth/resend-code", EmailRequestCodeView.as_view()),
    path("t/<slug:tenant_slug>/auth/email/request-code", EmailRequestCodeView.as_view()),
    path("t/<slug:tenant_slug>/auth/email/confirm", EmailConfirmView.as_view()),
    path("t/<slug:tenant_slug>/auth/phone/request", PhoneRequestView.as_view()),
    path("t/<slug:tenant_slug>/auth/phone/confirm", PhoneConfirmView.as_view()),
    path("t/<slug:tenant_slug>/auth/telegram/start", TelegramStartView.as_view()),
    path("t/<slug:tenant_slug>/auth/telegram/verify", TelegramVerifyView.as_view()),
    path("integrations/telegram/webhook", TelegramWebhookView.as_view()),
    path("t/<slug:tenant_slug>/client/me", ClientMeView.as_view()),
    path("t/<slug:tenant_slug>/client/operations", ClientOperationsView.as_view()),
    path("t/<slug:tenant_slug>/client/offers", ClientOffersView.as_view()),
    path("t/<slug:tenant_slug>/client/offers/use", ClientOfferUseView.as_view()),
    path("t/<slug:tenant_slug>/client/coupons", ClientCouponsView.as_view()),
    path("t/<slug:tenant_slug>/client/qr/issue", ClientQRIssueView.as_view()),
    path("t/<slug:tenant_slug>/client/profile/password", ClientPasswordChangeView.as_view()),
    path("t/<slug:tenant_slug>/loyalty/qr/validate", LoyaltyQRValidateView.as_view()),
    path("t/<slug:tenant_slug>/loyalty/points/earn", LoyaltyEarnView.as_view()),
    path("t/<slug:tenant_slug>/loyalty/points/redeem", LoyaltyRedeemView.as_view()),
    path("t/<slug:tenant_slug>/loyalty/points/refund", LoyaltyRefundView.as_view()),
    path("t/<slug:tenant_slug>/loyalty/ops", CashierOperationsView.as_view()),
    path("t/<slug:tenant_slug>/pos/loyalty/earn", POSLoyaltyEarnView.as_view()),
    path("t/<slug:tenant_slug>/admin/dashboard", AdminDashboardView.as_view()),
    path("t/<slug:tenant_slug>/admin/customers", AdminCustomersView.as_view()),
    path("t/<slug:tenant_slug>/admin/staff", AdminStaffView.as_view()),
    path("t/<slug:tenant_slug>/admin/staff/<int:user_id>", AdminStaffView.as_view()),
    path("t/<slug:tenant_slug>/admin/locations", AdminLocationsView.as_view()),
    path("t/<slug:tenant_slug>/admin/locations/<int:location_id>", AdminLocationsView.as_view()),
    path("t/<slug:tenant_slug>/admin/rules", AdminRulesView.as_view()),
    path("t/<slug:tenant_slug>/admin/rules/<int:rule_id>", AdminRulesView.as_view()),
    path("t/<slug:tenant_slug>/admin/operations", AdminOperationsView.as_view()),
    path("t/<slug:tenant_slug>/admin/offers", AdminOffersView.as_view()),
    path("t/<slug:tenant_slug>/admin/offers/<int:offer_id>", AdminOffersView.as_view()),
    path("t/<slug:tenant_slug>/admin/settings", AdminSettingsView.as_view()),
]
